name: Update Source Code on EC2

on:
  push:
    branches:
      - main  # 메인 브랜치에서의 커밋이 발생할 때 트리거

jobs:
  update-source:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}  # GitHub Actions 시크릿에서 SSH 키 사용
      run: |
        echo "$SSH_KEY" > private_key.pem
        chmod 600 private_key.pem

    - name: Check for dependency changes
      id: check_changes
      run: |
        # Check if package.json or package-lock.json has changed
        git diff --quiet HEAD^ HEAD -- package.json package-lock.json || echo "CHANGED=true" >> $GITHUB_ENV

    - name: Update Source Code on EC2
      env:
        EC2_SERVER_IP: ${{ secrets.EC2_SERVER_IP }}  # 서버 IP 주소도 시크릿에서 가져오기
        CHANGED: ${{ env.CHANGED }}
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key.pem ubuntu@${EC2_SERVER_IP} "
        cd /home/ubuntu/strapi-test &&
        git pull origin main &&  # 최신 소스 코드로 업데이트
        # Conditionally run npm install, build and restart pm2 if package.json or package-lock.json has changed
        if [ \"${CHANGED}\" == \"true\" ]; then
          npm install &&
          npm run build &&
          pm2 restart strapi-test-dev;  # PM2로 실행한 애플리케이션 이름으로 재시작
        fi"
